name: CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - run: dotnet restore
    - run: dotnet build --no-restore
    - run: dotnet test --no-build --verbosity normal
    - run: dotnet publish src/TelemetryHub.Server -c Release -p:PublishAot=true -p:PublishProfile=DefaultContainer
